import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "SMKN 1 Kawali",
  description: "Generated by create next app",
  keywords:
    "SMKN Kawali, IoT, Sekolah Teknologi, Pendidikan, Programming, Robotics, FathSchool",
  authors: [{ name: "SMKN Kawali" }, { name: "FathSchool" }],
  openGraph: {
    title: "SMKN 1 Kawali",
    description:
      "SMKN Kawali menyediakan pendidikan berbasis teknologi, pemrograman, dan inovasi digital.",
    url: "https://smknkawali.ac.id",
    siteName: "SMKN Kawali",
    images: [
      {
        url: "https://fathschool.smkn1kawali.sch.id/uploads/images/1730292468_67222af4ab529.jpg",
        width: 1200,
        height: 630,
        alt: "SMKN Kawali - Sekolah Teknologi & IoT",
      },
    ],
    type: "website",
  },
  // twitter: {
  //   card: "summary_large_image",
  //   site: "@smknkawali",
  //   title: "SMKN Kawali - Sekolah Berbasis IoT & Teknologi",
  //   description:
  //     "SMKN Kawali menyediakan pendidikan berbasis teknologi dengan fokus pada IoT, pemrograman, dan inovasi digital.",
  //   images: ["https://smknkawali.ac.id/og-image.jpg"],
  // },
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
